### PR TITLE
Better trim wheel support

### PR DESCRIPTION
**Pull request by kunajk**
see it on video: https://youtu.be/CeOAaXDspto

### CODE REVIEW

**Comment by sparker256** [comment]
Thanks for the pull request but I am trying to build this on my Ubuntu 18.04 LTS and can't get it to build.

I had to add #include <cmath> to make floor happy but now I get this error.

error: no matching function for call to ‘min(double&, float&)’

What did you build your changes on? My plugin is multiplatform and I build all three platforms on Linux so I need to get this to work somehow.

Thanks Bill

**Comment by kunajk** [comment]
Hello, first of all, I want you to thanks for great plugin. I build it on
windows(ms visual studio 2019). Hmm I believe this will be ok:
https://www.cplusplus.com/reference/cmath/fmin/
I made commit and i think it was added to current pull request(I'm not
familiar with git):
https://github.com/sparker256/xsaitekpanels/pull/11/commits/7d7da1cb23b2afc915ff787ddd498abd2eeb8b3c
Best regards,
Janusz

niedz., 9 maj 2021 o 21:28 William Good ***@***.***>
napisał(a):

**Comment by sparker256** [comment]
I got it to build on my Linux box by using this.

`#include <cmath>
#include <algorithm>`

I need to see what your xsaitekpanels.ini looks like so I can test further.

Bill

**Comment by kunajk** [comment]
I use default one. Here is new parameters. Most important is **Dynamic Trim Wheel - 0/1** thats enabled new mode: 
`; 0 - old mode; 1 - new mode enabled
Dynamic Trim Wheel = 1`

The rest parameters I used only for tweaking purpouses:

`;I think 10 is resonable maximum value
Dynamic Trim Max Val = 6

;Min shoudl be always 1
Dynamic Trim Min Val = 1

;If lower then wheel is more lazy. 0.5 is max value in my opinion
Dynamic Trim Acceleration Point = 0.3`

**Comment by kunajk** [comment]
Yes, correct

pon., 10 maj 2021 o 13:15 William Good ***@***.***>
napisał(a):

**Comment by sparker256** [comment]
Built for all three platforms and tested on them and all look good to me.

**Comment by kunajk** [comment]
Great, thank you very much

**Pull request merged**
